### ISSUE TITLE
Feedback Milestone 2

### ISSUE THREAD

**Issue by mkhfring** [data301-2021-summer2/project-group27-project#1]
Hello, Group 27, 

My name is Mohamad Khajezade, and I will be giving you some feedback on your project. 

This is a fantastic start, which shows your hard work on this project. However, there are some suggestions I have that will greatly improve the quality of your project."

I have divided up the feedback into several sections, so it is easier for you to implement.

## Task 1

- [1] The pipeline to load, clean, process, and wrangle the data was not completed, and you have jumped on task 3

## Task 2

- [1] You need to call your method changing in your notebook
- 
## Task 3

- [1 ] Most of your charts doesn't include any title, caption, or legend, and the purpose of using these charts is not clear  

## Task 4
- [1] Apart from charts and figures, you need to conduct some analysis that I couldn't find

**Comment by omurovec** [comment]
Thank you for the feedback! I'm still a little bit confused though about a few of your comments under tasks 1, 2 and 4, could you please explain a bit further what I'm missing? 

In task 1 I'm not sure what it is I'm missing to wrangle the data?

According to the milestone 2 instructions under task 2 it gives an example of how we should be loading the data into the notebook and calling the method chain which is exactly how I did in my first cell:
`df = project_functions.load_and_process()`

And for task 4 I'm not sure what analysis I'm missing, could you give an example or explain a bit further here?

Thanks

**Comment by mkhfring** [comment]
Hello,

I checked your project again. Sorry for missing your work for task1 and task2. I went to grade scope and changed my feedbacks for all of your tasks for milestone 2. The only thing that I can suggest to improve your project is to add some analysis to address your research questions. By analysis, I mean, for instance, calculating the sum of the trades for each currency, and then based on this sum, you conclude that this type of currency is more popular. Please let me know if you have any other questions. Sorry again for missing your project tasks. 

Cheers,
Mohamad

**Comment by omurovec** [comment]
Hi Mohamad,

Thank you for the clarification!

Sorry to bother you again but I just wanted to make sure I'm clear on task 4. I was under the impression that my analysis was covered throughout my section labeled analysis (located under my Exploratory Data Analysis). In the section, I answered my 3 research questions and provided new graphs to answer them as clearly as I could. Not sure whether you are suggesting I add another analysis or if the analysis I had provided was not sufficient for that section.

Again, sorry for the bother and I know it's somewhat last-minute but I want to be extra clear before I put in the time to make the adjustments.

Thanks,
Owen

**Comment by mkhfring** [comment]
Hello Owen,

Your work is perfect as far as I am concern. If you check your feedbacks on grade scope, you can see that you have exceeded expectations for each of these duties.  The suggestion is just to make it even better. Thus, the analysis that I mentioned is just a suggestion to add to your current works.

Cheers,
Mohamad

**Comment by omurovec** [comment]
I see, thank you!
